### ISSUE TITLE
More option to revoke a User statement

### ISSUE THREAD

**Issue by vanhtuan0409** [keys-pub/keysd#12]
During the testing period, I accidentally delete the gist statement and also the keys pair that used to create the statement

Now I cannot associate another keys pair with my Github account as it is required to revoke the last statement 1st.

I think it is better to provide some extra method to revoke a User statement, in-case of private key lots

**Comment by gabriel** [comment]
It may take up to 24 hours for search to re-check the statement and remove from search. And until then you wouldn't be able to publish another key for that user, which is a bug.

Thanks for reporting the issue.

**Comment by vanhtuan0409** [comment]
My statement is removed. Tks for let me know the information

**Comment by vanhtuan0409** [comment]
It is kind of unrelated but `keys auth` prompt me my password every time I open a new terminal (keysd is still running). I'm using Arch with Gnome Keyring unlocked

Is it possible to skip the prompt password if Gnome Keyring is unlocked?
