### ISSUE TITLE
org.freedesktop.secrets service dependency

### ISSUE THREAD

**Issue by gkelly** [keys-pub/keysd#8]
When trying to start `keysd`:

```
INFO[2020-04-28T21:48:53.258673747Z] Keyring (system)                                                                                                                                                                               
The name org.freedesktop.secrets was not provided by any .service files
```

Is the long-term plan to depend on the system keyring, or to provide a mechanism that doesn't?

**Comment by gabriel** [comment]
The long term goal is try try to use the system keyring and if that is unavailable, then to fall back to the filesystem based keyring.

(Currently you have to manually `config set keyring fs` to use filesystem keyring.)

**Comment by gabriel** [comment]
The latest versions will fall back to filesystem based keyring on linux.
